export interface QrGenerateRequest {
  /**
   * URL that the QR code will point to.
   */
  url: string;
}

export interface QrGenerateResponse {
  /**
   * URL of the QR code images that was generated by the model.
   */
  image_url: string;

  /**
   * Response latency in milliseconds.
   */
  model_latency_ms: number;

  /**
   * Unique ID of the QR code.
   * This ID can be used to retrieve the QR code image from the API.
   */
  id: string;
}
